In [18]:
import numpy as np
#0 Dimension array
a= np.array(1)

In [19]:
a

array(1)

In [20]:
print(a.ndim)

0


In [9]:
a= np.array([1,2,3])

In [10]:
a

array([1, 2, 3])

In [13]:
a= np.array([[1,2,7],[1,2,3]])

In [14]:
a

array([[1, 2, 7],
       [1, 2, 3]])

In [15]:
a= np.array([[[1,2],[1,2]],[[1,2],[1,2]]])

In [16]:
a

array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

In [17]:
print(a.ndim)

3


In [27]:
a= np.array([1,2,3,4],ndmin=1)

In [28]:
a

array([1, 2, 3, 4])

In [35]:
a[3]*2+a[2]

11

In [38]:
a= np.array([[1,2,7],[1,2,3]])
a[1,2]

3

In [42]:
a= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a[0,1,-2]

3

In [ ]:
# slicing


In [43]:
a=np.array([1,2,3,4,5])
a[1:4]

array([2, 3, 4])

In [44]:
a[1:]

array([2, 3, 4, 5])

In [45]:
a[:3]

array([1, 2, 3])

In [48]:
a[-3:-1]

array([3, 4])

In [49]:
# slicing step
a=np.array([1,2,3,4,5,6,7])
a[0:8:2]

array([1, 3, 5, 7])

In [50]:
a[::2]

array([1, 3, 5, 7])

In [51]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [54]:
a[0,0:6:2]

array([1, 3, 5])

In [58]:
a[0:2,3]

array([4, 9])

In [60]:
a[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [61]:
a.dtype

dtype('int32')

In [67]:
a=np.array([1.1,1.2,1.7])
a

array([1.1, 1.2, 1.7])

In [68]:
new=a.astype(int)

In [69]:
new

array([1, 1, 1])

In [71]:
new.astype(complex)

array([1.+0.j, 1.+0.j, 1.+0.j])

In [72]:
a=np.array([1,2,3,4,5,6,7])
a[0]=2

In [73]:
a

array([2, 2, 3, 4, 5, 6, 7])

In [74]:
x=a.copy()

In [75]:
x

array([2, 2, 3, 4, 5, 6, 7])

In [76]:
y=a.view()

In [77]:
y

array([2, 2, 3, 4, 5, 6, 7])

In [78]:
y.shape

(7,)

In [79]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [80]:
a.shape

(2, 5)

In [107]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
a.reshape(-2,6,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]])

In [108]:
# itterate in one dimension
a=np.array([1,2,3])
for x in a:
    print(x)

1
2
3


In [110]:
# itterate in two dimension
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in a:
    for y in i:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [113]:
# itterate in three dimension
a= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for i in a:
    for s in i:
        for z in s:
            print(z)

1
2
3
4
5
6
7
8


In [114]:
# concatenation in one dimension
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))

In [115]:
c

array([1, 2, 3, 4, 5, 6])

In [127]:
# concatenation in two dimension on column using axis=1
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
c=np.concatenate((a,b),axis=1)

In [128]:
c

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [129]:
# join using stack()
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack((a,b))


In [130]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
# using join for hstack
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))


In [132]:
c

array([1, 2, 3, 4, 5, 6])

In [133]:
#dstack mean depth
c=np.dstack((a,b))

In [134]:
c

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [141]:
a=np.array([1, 2, 3, 4, 5, 6])
b=np.array_split(a,10)
b

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]

In [142]:
b[2]

array([3])

In [147]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])
c=np.hstack((a))
np.array_split(c,3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [150]:
a=np.array([1, 2, 3, 4, 5, 6])
b=np.where(a==6)
b

(array([5], dtype=int64),)

In [151]:
b=np.where(a%2==0)

In [152]:
b

(array([1, 3, 5], dtype=int64),)

In [159]:
c=(np.searchsorted(a,3,side='right'))

In [160]:
c

3

In [165]:
c=np.sort(a)

In [162]:
c

array([1, 2, 3, 4, 5, 6])

In [166]:
a

array([1, 2, 3, 4, 5, 6])

In [168]:
# filtering 
x=[True,False,True,False,False,True]
a[x]

array([1, 3, 6])